apiVersion: v1
items:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: coolstore
      app.kubernetes.io/instance: web
      app.kubernetes.io/name: nodejs
      app.kubernetes.io/part-of: coolstore
    name: web-coolstore
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: {}
    output:
      to:
        kind: ImageStreamTag
        name: web-coolstore:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: labs/web-nodejs
      git:
        ref: "3.0"
        uri: https://github.com/mcouliba/cloud-native-workshop
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs:10-SCL
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers: []
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
