---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: oc-deploy
spec:
  inputs:
    params:
      - name: appName
        default: sample
        description: The name of the application
  steps:
    - name: oc-deploy
      image: quay.io/openshift/origin-cli:latest
      command: 
        - "/usr/bin/oc"
      args:
        - rollout 
        - latest 
        - '$(inputs.params.appName)'